### ISSUE TITLE
List Builder plugin - the list showing as table in the Review/Summary page not very user friendly and needs improvement, so it should show in a better layout for inner list is existing

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/conforma-web-app#1042]

**Comment by CarlosNZ** [comment]
This should show in the Summary page in the same format that it's been configured for in the main application. Is it not?

**Comment by nmadruga** [comment]
I'll get some examples for use to compare

**Comment by nmadruga** [comment]
Inner list showing on a list item (before adding/while editing) - Nice view
![Screen Shot 2021-11-18 at 3 00 27 PM](https://user-images.githubusercontent.com/16461988/142337653-f1be3fdf-738e-41f1-b85c-3405e8450967.png)

Inner list showing as plain text in the outer list on the Summary page - ugly view
![Screen Shot 2021-11-18 at 3 00 34 PM](https://user-images.githubusercontent.com/16461988/142337647-99fc0adc-fbfb-4377-a074-f17eef83c3d0.png)

Review page (same as Summary) - ugly view
![Screen Shot 2021-11-18 at 3 02 21 PM](https://user-images.githubusercontent.com/16461988/142337746-00bb6f14-a54f-48a2-bc5d-d45e2219e3d3.png)

**Comment by CarlosNZ** [comment]
Okay, thanks, I expect this is a fairly simple fix. Will do now.

**Comment by CarlosNZ** [comment]
Okay, so the screenshots you've posted are actually two different views -- the first one is what you see when you actually click on one of the formulations in the table, but the table itself is the same in both Application and Summary views.

However... the Summary view is not clickable like the Application view, so you can't "pop-up" the nice view. So if I just make that the Summary view is also clickable and so can view the "nice" view of each item in the table, that should do the trick, right?

Also -- I *think* (I'll need to check) that the "plain text" in the Ingredients list cell can be formatted/edited more nicely, although I may have forgotten to document it (it was a last-minute addition for a previous demo). I'll look into that and update the docs if need be -- but you should be able to make the cell just show something like "Substance: asapiprant...click row for details", which will be nicer :)

**Comment by nmadruga** [comment]
> Okay, so the screenshots you've posted are actually two different views -- the first one is what you see when you actually click on one of the formulations in the table, but the table itself is the same in both Application and Summary views.

Yes, correct. Sorry that wasn't very clear

**Comment by nmadruga** [comment]
> So if I just make that the Summary view is also clickable and so can view the "nice" view of each item in the table, that should do the trick, right?

No, I think that's not what is expected, instead all of the Summary view should show inner list as a inner plugin instead of plain text. If that's possible to do

**Comment by nmadruga** [comment]
> I'll look into that and update the docs if need be -- but you should be able to make the cell just show something like "Substance: asapiprant...click row for details", which will be nicer :)

Cool! I'm keen to see that, it might be the easiest solution. Do you think it would be possible to set that as the default?

**Comment by CarlosNZ** [comment]
> Cool! I'm keen to see that, it might be the easiest solution. Do you think it would be possible to set that as the default?

Yeah maybe, I'll have to check how it works again. I might be getting confused with the Search plugin, but if so I can use the same solution here.

**Comment by CarlosNZ** [comment]
Text can be formatted as required now
