### ISSUE TITLE
Show categories under menu of "Applications list" and child categories as sub-menus

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/conforma-web-app#1056]
Discussed in catch-up meeting with team on 25/11/2021

## Summary
Basically, change from how we currently show full list of applications:
![Screen Shot 2021-11-25 at 11 07 56 AM](https://user-images.githubusercontent.com/16461988/143318786-0e8e3c20-454c-4c30-8e8d-f63c963c849f.png)

* Change to show each category (if any) and then the applications as sub-menus. 

### Restrictions
If no category exists for that template, would just show the template in the same menu as other categories.
If category doesn't have any template with permissions to current logged user - don't show the category!

**Comment by CarlosNZ** [comment]
Similarly, allow nested categories for Database views (and maybe other menus)
