### ISSUE TITLE
Misc bugs during review process

### ISSUE THREAD

**Issue by CarlosNZ** [openmsupply/conforma-web-app#1081]
Jess noticed some issues yesterday, so I'm going through the review process in detail and I'll note any issues I find here:

- "NOT FOUND" stage in History:
![Screen Shot 2022-01-20 at 12 05 21 PM](https://user-images.githubusercontent.com/5456533/150232602-ac6666d8-233b-43b0-bc3d-532a80b77e70.png)
What is this for? What should it be? (Note: This disappears after the application had moved into Assessment stage)

- Self-assigned a section, but shows as "Not Assigned":
![Screen Shot 2022-01-20 at 12 12 29 PM](https://user-images.githubusercontent.com/5456533/150233435-5e27fb5d-e17b-4748-bc22-a6936d6bf5f2.png)

- Not showing who the other Section is assigned to (I'm logged in as Senior Reviewer, other section has been assigned to Admin)
![Screen Shot 2022-01-20 at 12 18 21 PM](https://user-images.githubusercontent.com/5456533/150234018-783cf414-55f8-4dde-8c4c-587a39032c8a.png)
(Also, having it in blue is confusing, since it's not actually a link)

UPDATE on 11/02/2022: Next 3 issues should be fixed in PR #1113 👇 

- Senior Reviewer has completed their application. But now "Admin" can see a "start" link for reviews that are already completed:
![Screen Shot 2022-01-20 at 12 24 57 PM](https://user-images.githubusercontent.com/5456533/150234559-bf196836-bfae-4ab5-97c7-ac2e59b272bc.png)
It might be because Admin has a section assigned to them which they haven't yet started, so it's displaying "Start" on all sections erroneously. Don't think the self assign link should be visible though. (Note: doesn't show up in the Dashboard "available for self-assignment" filter, so it's being filtered correctly there)

- Following on from previous, when I (as Admin) "start" one of the sections I'm not assigned to, it looks like the review that's created is correct (i.e. can only review the section that I've been assigned). However, all the other sections still say "Assigned to you" even though they aren't:
![Screen Shot 2022-01-20 at 12 30 23 PM](https://user-images.githubusercontent.com/5456533/150235038-52d216cb-954f-4e94-bf3c-00bd74a78fd4.png)

- Continuing -- when I try and submit review (as Admin), I get a warning that I haven't completed Section 1 -- even though I'm not assigned to it, and it's already been completed (by Senior Reviewer)
![Screen Shot 2022-01-20 at 12 31 44 PM](https://user-images.githubusercontent.com/5456533/150235319-ea22f29c-8fd3-4e06-aa0f-7287190da55d.png)
But there's no button to actually review it, so I'm stuck now.

There's probably more, but I'll leave it at that for now. I think a lot of this is caused by having a user who has permission for both levels of review -- the UI gets very confused. I'll try again and make sure level permissions are separated out and see what happens

**Comment by CarlosNZ** [comment]
> I think a lot of this is caused by having a user who has permission for both levels of review -- the UI gets very confused. I'll try again and make sure level permissions are separated out and see what happens

Yes, it seems to the case.

**Comment by CarlosNZ** [comment]
Okay, so the one bug that remains after making the permissions exclusive (i.e. no reviewer can do more than one of assign, review or consolidate) is this one:

> * Continuing -- when I try and submit review (as Admin), I get a warning that I haven't completed Section 1 -- even though I'm not assigned to it, and it's already been completed (by Senior Reviewer)
>       ![Screen Shot 2022-01-20 at 12 31 44 PM](https://user-images.githubusercontent.com/5456533/150235319-ea22f29c-8fd3-4e06-aa0f-7287190da55d.png)
>       But there's no button to actually review it, so I'm stuck now.

**Comment by nmadruga** [comment]
> * ![Screen Shot 2022-01-20 at 12 05 21 PM](https://user-images.githubusercontent.com/5456533/150232602-ac6666d8-233b-43b0-bc3d-532a80b77e70.png)
>   What is this for? What should it be? (Note: This disappears after the application had moved into Assessment stage)

That's a bug noticed before #946 the Not found is when there is no Stage set for the review_response. The stage is only set after the response has been submitted. And what this is showing is a Draft response. It basically shouldn't be showing

**Comment by nmadruga** [comment]
> * Not showing who the other Section is assigned to (I'm logged in as Senior Reviewer, other section has been assigned to Admin)
>   ![Screen Shot 2022-01-20 at 12 18 21 PM](https://user-images.githubusercontent.com/5456533/150234018-783cf414-55f8-4dde-8c4c-587a39032c8a.png)

This happens when the section is not reviewable - since none of the questions have been answered by applicant. We chatted in person yesterday and though we could change to always add a reviewer even thought there is nothing to review. But this may require some more thinking...

>   (Also, having it in blue is confusing, since it's not actually a link)

It was how the Designer had suggested to do. Anything in blue with the dot are meant to be "calling your attention" as what you should be doing in this page. In this case, is starting the review.

**Comment by nmadruga** [comment]
> There's probably more, but I'll leave it at that for now. I think a lot of this is caused by having a user who has permission for both levels of review -- the UI gets very confused. I'll try again and make sure level permissions are separated out and see what happens

I wonder if this problems are caused because we added the "Final decision" level as part of the same stage and Admin has this permission too. It will be really good to test without this permission in place.

**Comment by nmadruga** [comment]
> Okay, so the one bug that remains after making the permissions exclusive (i.e. no reviewer can do more than one of assign, review or consolidate) is this one:
> 
> > * Continuing -- when I try and submit review (as Admin), I get a warning that I haven't completed Section 1 -- even though I'm not assigned to it, and it's already been completed (by Senior Reviewer)
> >   ![Screen Shot 2022-01-20 at 12 31 44 PM](https://user-images.githubusercontent.com/5456533/150235319-ea22f29c-8fd3-4e06-aa0f-7287190da55d.png)
> >   But there's no button to actually review it, so I'm stuck now.

Does that happens always when you have more than one reviewer, or only after re-review if the consolidator has asked for changes?

**Comment by CarlosNZ** [comment]
Done
