### ISSUE TITLE
Bug: Error to user not logged off when trying to click link to reset password

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/conforma-web-app#1154]

**Comment by nmadruga** [comment]
Happening during the create internal user workflow - when there is already an user logged in the system. And another problem happens even if the user logged out before clicking on the link (after user is created). Which doesn't load the application resetPasssword correctly.

A very basic way to fix this is always clear the JWT of the user when they are requesting to run the ResetPassword template.

**Comment by nmadruga** [comment]
Should also be fixed (old problem) when loading UserRegistration - after logged out from another account - the page doesn't load and show this error:
<img width="947" alt="Screen Shot 2022-04-23 at 4 45 53 PM" src="https://user-images.githubusercontent.com/16461988/164878105-5538c447-67e7-43be-a9b0-25a872ad5956.png">

**Comment by CarlosNZ** [comment]
> A very basic way to fix this is always clear the JWT of the user when they are requesting to run the ResetPassword template.

You should only be able to access the RequestPassword template from the login page, which you can only get to when you're logged out. And when you're logged out, the JWT should already be cleared. If that's not happening, then it's not behaving as intended.

> Should also be fixed (old problem) when loading UserRegistration - after logged out from another account - the page doesn't load and show this error:

Yeah, I can never seem to reliably replicate this. Do you know the steps required to always get this error? That would make it a lot easier to pin down.

**Comment by CarlosNZ** [comment]
Also -- I can't actually replicate the main issue here anymore. Can someone describe the steps to replicate it?
