### ISSUE TITLE
Improve message displayed to reviewer to help with decision 

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/conforma-web-app#1160]
1. Add warning next to button to **Reject** (when selected) only for reviewer 1 - should check the level. To say something about this will go to Applicant in case it's send as LOQ.

2. Change overall comment as markup text - if possible....

After changed the Portuguese to this:
`"LABEL_REVIEW_OVERALL_COMMENT": "Comentário geral:\n Se for selecionado \"Em confomidade\": Favor inserir um comentário para anotações internas da decisão interna.\n Se for selecionado \"Observações\": Favor inserir um comentário com o resumo de anotações da decisão interna.\nSe for selecionado \"Não-conformidade\": Favor inserir os detalhes com os motivos da rejeição deste formulário.\n"`

It doesn't show as expected:
<img width="752" alt="Screen Shot 2022-04-27 at 9 16 51 AM" src="https://user-images.githubusercontent.com/16461988/165473533-802663c4-611e-41a5-8ae2-7abe833d73ae.png">

[Updated 12/08/2022 by Nicole] Bringing this from another issue - with another version of decision's descriptions
---

From issue https://github.com/openmsupply/conforma-server/issues/724:

To improve the user experience with the overall comment box.
-----------
Update 1:
Can the following please be added:
The text above overall comment be changed to:
_‘Overall comment
If application outcome is 'Conform': Please use this field to include a summary of the internal decision notes.
If application outcome is 'Request information from the applicant': Please use this field to include a summary of the internal decision notes.
If application 'Non-conform': Please use this field to detail the reasons for rejection to the applicant.'_

<img width="514" alt="image" src="https://user-images.githubusercontent.com/88009219/164971928-b803505a-6951-4a75-a9a2-332fb00996b1.png">

------------
Update 2:

Can the decision radio button for list of questions be amended as follows to help internal staff:
List of questions to _'Request information from applicant. Note: Any non-conforming comments will be displayed to the applicant for actioning."_

**Comment by nmadruga** [comment]
> Generally it's more straightforward to make separate messages for each line, since you'd expect each language to have the line breaks in the same place.

That could be a good way to go : ) I'll see if I can include this on my todo list for tomorrow - too big list already for today

**Comment by nmadruga** [comment]
Do this as part of this issue: https://github.com/openmsupply/conforma-server/issues/724

**Comment by nmadruga** [comment]
> 1. Add warning next to button to **Reject** (when selected) only for reviewer 1 - should check the level. To say something about this will go to Applicant in case it's send as LOQ.

I believe this will not be required now that we have the preview @jagoje?

**Comment by jagoje** [comment]
I like this - though hahaha
