### ISSUE TITLE
Assignment problems - found during field trip (April)

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/conforma-web-app#1161]
- [ ] Bug: When Final-decision already auto-assigned should show the Assignment box
<img width="893" alt="Informações do produto" src="https://user-images.githubusercontent.com/16461988/165475000-c2133322-cae4-4cf1-b476-609283da52ba.png">

- [x] After the application outcome is approved shouldn't be showing as possible to assign. Fixed in #1169
<img width="1357" alt="Screen Shot 2022-04-27 at 9 12 44 AM" src="https://user-images.githubusercontent.com/16461988/165475138-b238b20a-26eb-4b2b-a498-74cf909fc98e.png">

**Comment by CarlosNZ** [comment]
Ah yes, this should ideally also be taken care of when we fix #1166 properly -- see [this comment](https://github.com/openmsupply/application-manager-web-app/pull/1166#discussion_r860897002) for what I'm getting at.

I think piling on a bunch of band-aid fixes like we've been doing is not helping us any more and is creating more and more problems -- we need to re-assess how the whole review progress / review response status, etc. logic works, and hopefully make it a lot clearer and simpler

**Comment by CarlosNZ** [comment]
Also -- we don't store what the "current" review level is in state at all (as far as I can tell), so there's no way to check whether a level has passed or not. Is there?

**Comment by CarlosNZ** [comment]
The action in the List comes directly from the server, so that'll need to be a back-end issue.

**Comment by CarlosNZ** [comment]
> Also -- we don't store what the "current" review level is in state at all (as far as I can tell), so there's no way to check whether a level has passed or not. Is there?

I'm thinking that we might need to have more back-end state for applications, which is all compiled in once place/field, and the front-end just reads it and doesn't have to handle all this complicated logic. I'll keep having a think, let's discuss later.

**Comment by nmadruga** [comment]
> I'm thinking that we might need to have more back-end state for applications, which is all compiled in once place/field, and the front-end just reads it and doesn't have to handle all this complicated logic. I'll keep having a think, let's discuss later.

2 things to add:
> Also -- we don't store what the "current" review level is in state at all (as far as I can tell), so there's no way to check whether a level has passed or not. Is there?

We already show in the UI (first column) when the review is submitted, so the only time we would see both reviews (consolidation and review) as current would be one application that review has not started, but the consolidation has (due to another section being already submitted)

**Comment by nmadruga** [comment]
Even though, to have this simplified for the front-end we could actually have a function to return actions (and the create a better mechanism to keep which is the current level) to be returned from the back-end. Although the current level should still allow more than one level to work at the same time, as exemplified before:
- There are 3 sections that are assigned to different reviewers
- Section 1 is submitted - now the consolidation can be assigned/started
- At this moment there are 2 reviewers that can start/continue level 1 and consolidation (for section 1) that can start/continue
