### ISSUE TITLE
Add/Update links to documents for consultation on the App

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/conforma-web-app#1177]
IMPORTANT: PSM Replied with Approved and recommended to be in initial MVP (02/06/2022)

### Reference
**Final Requirements Matrix 2** - Customisations - Row 2

### Requirement discussion
Guidance documents and information to be clearly and easily accessible within Conforma, for both internal and external users.
Requires the ability for local staff to be able to easily update documents, and have document control.
Could display documents in a look up table style, within a ‘help menu’.
Discussed with GHSC-PSM as a desired customisation.

**Comment by nmadruga** [comment]
**- Have the SOP included in the system accessible internally**

**Comment by CarlosNZ** [comment]
### Suggested solution

We designate a particular subfolder in "files" to be for reference docs. Let's call it "reference". 

Any files in that folder get automatically shown in the "Help" menu (we might need a "is_reference_doc" field in the file table to make the search quicker).

We create a template called "Manage reference docs" which shows the user;

- checklist of currently uploaded docs, with checkboxes to disable ones no longer required
- upload element for adding new docs (with the "subfolder: reference" parameter set)

On submit, any documents in the checklist which are no longer checked are deleted.

### Questions:

- Do we want to allow a nested folder structure, which would then be shown as sub-menus in the "Help" menu? This would add a bit more complexity, so would rather not if it's not essential
- Do we want to be able to mark documents as "disabled" (so they no longer show up) without fully deleting them?

**Comment by jagoje** [comment]
Just some responses below:

Questions:
Do we want to allow a nested folder structure, which would then be shown as sub-menus in the "Help" menu? This would add a bit more complexity, so would rather not if it's not essential

_Nup, simple with each document being stored under the main menu is A OK_

Do we want to be able to mark documents as "disabled" (so they no longer show up) without fully deleting them?

_I do not think this is important - I think clearing from the system is ok_


Also just as a final point, to allow for different documents to be viewed by internal and external users it would be easier to have two seperate menus (e.g. One for external users, and internal users)

**Comment by jagoje** [comment]
Hi only one minor issue noted upon submission (when uploading documents) all other testing was a success! Hoorah

Testing sheet: https://docs.google.com/spreadsheets/d/1WNYioUsIbIdfW9ICYNAdQFT0cIH7s6aebnlgWonCq48/edit#gid=0
