### ISSUE TITLE
Improvement: Activity log missing informations

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/conforma-web-app#1178]

**Comment by CarlosNZ** [comment]
More info?

**Comment by nmadruga** [comment]
Haha sorry - I do have a picture!

... where is it?

Here you go:

<img width="1512" alt="Screen Shot 2022-04-29 at 12 25 18 PM" src="https://user-images.githubusercontent.com/16461988/168038886-33dec81c-c9f8-4381-aef8-1e62fff5e5fb.png">

**Comment by nmadruga** [comment]
Also noticed something not correct about which sections have been assigned, didn't we have something to say which ones were assigned?

**Comment by CarlosNZ** [comment]
The `%3` is a translation typo -- here is your Portugese string:
```
"TIMELINE_REVIEW_ASSIGNED": "%1 foi atribuído por %3 para revisão de %3",
```
(duplicate `%3`) ;)

Feel free to fix that directly on `develop`

> Also noticed something not correct about which sections have been assigned, didn't we have something to say which ones were assigned?

Yes, it should say the sections that were assigned -- can you show a case where it doesn't?

**Comment by nmadruga** [comment]
> The %3 is a translation typo -- here is your Portugese string:

> "TIMELINE_REVIEW_ASSIGNED": "%1 foi atribuído por %3 para revisão de %3",

Thanks, Carl! I'll do this change tomorrow. 

> Yes, it should say the sections that were assigned -- can you show a case where it doesn't?

I can see that's all good!
![Image](https://user-images.githubusercontent.com/16461988/187120420-0433e297-b553-45df-b104-827fbf3e1492.png)


There is just one more I noticed in this same area. After the Screening on P1-ProdRegistration was submitted, it was showing on the next stage, for some reason.... I'm not sure this might be due to config changes.

![Image](https://user-images.githubusercontent.com/16461988/187120412-fd32ea2c-36cb-4021-aa31-2ca9453c4964.png)

**Comment by nmadruga** [comment]
Done on latest snapshot - only required config changes.
