### ISSUE TITLE
Future implementation (Due date): Add a time limit for applications to be responded to applicants

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/conforma-web-app#1183]

**Comment by CarlosNZ** [comment]
We should be able to do this with configurations:
- set an expiry when review requests changes
- on expiry, change application status, send notification

**Comment by nmadruga** [comment]
Well - it need to have a bit more logic. What has been discussed about this was:

- The time for replying to applicant will start counting after approved to Stage 2.
- The time to get a response from FDA is defined on the email sent at this point
- The decision that stops the clock is the one done on Stage 3.

**Comment by CarlosNZ** [comment]
> Well - it need to have a bit more logic. What has been discussed about this was:
> 
> 
> 
> - The time for replying to applicant will start counting after approved to Stage 2.
> 
> - The time to get a response from FDA is defined on the email sent at this point
> 
> - The decision that stops the clock is the one done on Stage 3.

Cool -- pretty sure all that can be done with config. Will have to try it to be sure, but I think scheduled actions can handle all those scenarios.

**Comment by CarlosNZ** [comment]
Done, I think
