### ISSUE TITLE
To allow for internal staff to review elements in the form that have not been filled by applicants.

### ISSUE THREAD

**Issue by CarlosNZ** [openmsupply/conforma-web-app#1199]
### Reference

Final Requirements Matrix - Customisations - Row 1

* 4 days of development + tests
* 1 day review/documentation

### Requirement discussions
As discussed at recent meeting, we need a way to allow certain questions to be optionally:

- reviewable, even when there is no applicant response
- NON reviewable even when there IS a response (eg the checkbox array tied to the file upload)

My suggestion would be to add a new field to template_element schema called is_reviewable (along with is_visible, etc.) with three possible states:
- NULL (default), behaves same as it does currently
- true -- always reviewable regardless of applicant response
- false -- never reviewable, regardless of applicant response

For the "true" case, the way to make it work would be to generate a blank default response when the application is created, which will ensure that application responses are not pruned and associated review_responses are created.

For the "false" case, we check during creation of review responses, and don't make one if this field is "false"

Slight problem: this seems like it would be mainly back-end logic, so this field wouldn't be able to be dynamic like all the others. I would think that this is probably fine, but it bothers me slightly that this is inconsistent with other similar fields (is_visisble, is_required, is_editable, etc). Will have a bit more of a think about it.

--- 

### Issues (as per [suggested solution](https://github.com/openmsupply/conforma-web-app/issues/1199#issuecomment-1174445626) below):

- [x] https://github.com/openmsupply/conforma-server/issues/782
- [x] #1229
- [x] #1230
- [x] #1231

**Comment by nmadruga** [comment]
First idea
- Show all non-filled questions as pre-Approved which allows the reviewer to change to Reject as request some answer
- This means that a reviewer that was assigned to a Section WITHOUT any filled questions would now have to submitted their review.
- Potential of confusion around pre-approved fields... In the UI we can hide these somehow (and have a palce for thenm to edit) based on an ApplicationResponse being Null and the ReviewResponse is Approved
- 🔝 would be a possible problem for Consolidation

Second idea:
- Create the ApplicationResponse within the new ReviewResponse when the reviewer selects to add a review to the non-filled question. 
- For reviewers assigned to sections that don't have any answered questions it doesn't show as possible to start. This needs to change so the reviewer can start and review something that was required to be answered
- The box to give the reviewResponse requires this to be created already, we would need to allow the decision to be made before we create the ReviewResponse + ApplicationResponse. 
- Those ApplicationResponse (Null) that were created by a new ReviewResponse shouldn't be trimmed during the action that rips out ApplicationResponses not filled (e.g: when Applicant Re-submits)

**Comment by CarlosNZ** [comment]
### Suggested solution:

Based loosely on what is written in original comment.

1. Add two new fields to "template_element" table:
- `is_reviewable`, with possible (enum) values of "ALWAYS", "NEVER" and `null` -- default null, which would behave the same as it does currently
- `review_required` -- boolean (default `true` -- same as current behaviour)
The reason why there is two fields rather than an additional "SOMETIMES" value in the first one is that the issue of whether a review is optional is for when an applicant has made a response. Wheras the first one (is_reviewable) is about whether review can interact with a response regardless of whether the applicant has answered it. Thinking that things like names, perhaps, could be not required for review. This second one is less important, but could be useful in some cases.

2. Changes to "trimResponses" logic: when trimming application response (trimResponses action), we also check if an application response is linked to a template_element whose `is_reviewable` value is "ALWAYS", and don't trim those that are.
3. Change to `useCreateReview` hook (front-end): when creating review responses, we *don't* create them for ones that are linked to template_elements that have `is_required` = NEVER. (Hopefully this info will be easily available from the review/application structure)
4. This will require a bit more investigation (to do before starting this any development on this epic), but need to ensure:
- reviews that don't have responses don't have a "review" UI in review page (should it show anything?)
- review can be submitted if reviewer has not answered questions that are `review_required: false` (this wouldn't work currently -- all responses need to be answered)
5. There may be some funky things that happen with application re-submissions etc,. so will need to test the front-end logic very carefully with the above changes

**Comment by CarlosNZ** [comment]
Just a small update on this:

- seems like it's pretty simple to add the "is_reviewable" field as described above, with the "ALWAYS", "NEVER", and null options, and the front-end can be made to work with fairly minimal changes. And that part is the actual *required* feature, so that's good.
- the other one, making items *optionally* reviewable is not so straightforward. I haven't explored it fully yet, but it's definitely not as simple as the first part. And since this is not actually a requirement, it might be better to give it a miss. I'll keep trying for a bit but if it keeps causing more problems than it solves, we should probably put this on the back-burner for a while. Will update once I've looked a bit further.

**Comment by nmadruga** [comment]
To allow the reviewer to start, wince there would be no `applicationResponse` it wouldn't allow to start the application.
It will need to change the `isReviewable` condition to also include `optionalReviewable` to be considered.
