### ISSUE TITLE
Improvement: Under maintenance page to be displayed while server has new snapshot loading

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/conforma-web-app#1202]
BUG: When someone is using the system if we go to the Templates page - there is an error display for the other user! We need to have a way to at least display that the system is under maintenance and will be back to live shortly.

**Comment by CarlosNZ** [comment]
Close this now? Andrei has fixed.

**Comment by CarlosNZ** [comment]
Thoughts on this: 

yes, it would be good to have some kind of alert for the user when we upgrade or change the server, particularly during development. If we "lock" the app when we load a new snapshot, it'll save us the hassle of telling the rest of the team that it's happening and that it's finished. (i.e. You set app to "maintenance" mode, download snapshot, make changes, then re-upload, then set back to "normal" mode, so no one wastes time making changes that are going to get overwritten).

However, it's definitely not trivial to do. It would need to be set by the server, but how does the front-end know about it without polling an endpoint periodically? 

Would need to plan/discuss this a bit more, as it's fairly complex to do well, I think.

**Comment by CarlosNZ** [comment]
Seems low priority now that snapshot loading is so fast. (And we should never be doing it on a live server anyway)
