### ISSUE TITLE
Configurable per Stage/Level/Decision preview or link on Review submission

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/conforma-web-app#1210]
Child of #1203 

### Reference

Final Requirements Matrix - Customisations - Row 2

### Requirement discussion
Send to the action the list of question (and the answers as text) to be included in the generated Carbone template
- Setup Carbone template for LOQ example
- Preview might be not possible, we should use a link to the pdf
- How to generate the PDF once the reviewer clicks to preview? 
  - It can be using the End-point or it can be using the action based on a new EVENT...

**Comment by CarlosNZ** [comment]
Closing, replaced by issues related to agreed solution (most are in back-end)
