### ISSUE TITLE
Show message to user unassigned to review on the ReviewPage

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/conforma-web-app#1214]
IMPORTANT: PSM wrote: Approved and recommended to be in initial MVP (02/06/2022)

### Reference 

**Final Requirements Matrix 2** - Customisations - Row 12 

### Requirement discussion
- [x] Fix https://github.com/openmsupply/conforma-web-app/issues/1216 (Not requested - but should helps to remove confusion)
It's an edge case, since usually the re-assignment is done because the original reviewer is not working on the review, but it happened during a workshop. and it's confusing to the person reviewing when try to submit and nothing happens.

**Comment by CarlosNZ** [comment]
I'm not 100% clear on this. Is it just for reviewers who *already started* a review and have now been unasasigned, or for anyone who had been assigned regardless of how briefly?

**Comment by CarlosNZ** [comment]
Oh, thanks Nicole, that makes sense. So it would only show up for reviewers who had already started a review -- since they wouldn't be able to start a new one if they've been unassigned.

👍

**Comment by nmadruga** [comment]
It seems the actions to make this work needs a bit of tweaking first. We used to have an event ON_REVIEW_REASSIGN that got removed and now should work on REVIEW_ASSIGN and ON_REVIEW_UNASSIGN. But currently the `changeStatus` to make an existing Review to DISCONTINUED status doesn't work since the action fails. To check this problem please load the snapshot on `dev/snapshots/Unassignment_warning_test` then load Page: http://localhost:3000/application/S-OSW-0002/review?tab=assignment as user `jess` and try "Un-assigning" see the error on the Back-end:
```
Changing the Status of Review 2...
cannot accumulate empty arrays
```

**Comment by nmadruga** [comment]
This is the error I get (after trying to run the action `changeStatus`) if I try to do the same straight in Postgres:
![Screen Shot 2022-09-06 at 10 06 20 AM](https://user-images.githubusercontent.com/16461988/188516212-bd10dc17-f904-4020-80e6-aa5dcd7e9530.png)

**Comment by nmadruga** [comment]
Ok - Bug is fixed in Back-end and now I was able to finish up this Un-assigning message. The only missing part (to be done in the afternoon) will be to add the non-currently-existing actions in ProdRegistration to actually Un-assign and Re-assign sections as it is doing on the test snapshot: `dev/snapshots/Unassignment_warning_test`

**Comment by jagoje** [comment]
Reopening. Was able to get two people working on it at the same time and submit an outcome.. The system did not like that!

**Comment by nmadruga** [comment]
Closing - have been fixed in latest snapshot and uploaded to instance 50008
