### ISSUE TITLE
Handling applications that are past their due date for applicant response

### ISSUE THREAD

**Issue by jagoje** [openmsupply/conforma-web-app#1225]
Some work needs to be done to handle how applications can be handled once the due date for response from the applicant has lapsed. 

Some basic notes:
- Extensions are common.. I do no think automatic rejection is the best way to go.
- It would be good if the Regulator could push the application back to be with the internal users, to allow for rejection. 
---

See [agreed solution](https://github.com/openmsupply/conforma-web-app/issues/1225#issuecomment-1178466161) below

**Issues:**

**Back-end:**

- [x] https://github.com/openmsupply/conforma-server/issues/784
- [x] https://github.com/openmsupply/conforma-server/issues/785
- [x] https://github.com/openmsupply/conforma-server/issues/786
- [x] https://github.com/openmsupply/conforma-server/issues/787

**Front-end:**

- [x] #1236 
- [x] #1237
- [x] #1238

**Comment by CarlosNZ** [comment]
I'm thinking -- we can use the existing scheduled actions functionality to set and track expiry. We set the application "Outcome" to "EXPIRED" when time runs out.

So we just need a mechanism for regulator to:
- extend the expiry date before it expires
- "Unexpire" an application (i.e. set its outcome back to "PENDING")

I'm thinking this should be done with some additional UI on the the Review home page.

We also need to know how to make sure the applicant is informed of due date. Options:
- Put the due date in the email that comes with the LOQ request
- Show the due date on the Application list
- "Header" banner within the application itself

**Comment by jagoje** [comment]
@CarlosNZ 

I think for simplicity at the moment.. it would be good just to keep to un-expire one that has already run out? I think the extend a deadline will take more work (correct me if I am wrong though)?

On that note - due dates will be part of the emails and LOQ letter if helpful, which sounds like the easiest way to go for now.

**Comment by CarlosNZ** [comment]
> I think for simplicity at the moment.. it would be good just to keep to un-expire one that has already run out? I think the extend a deadline will take more work (correct me if I am wrong though)?

Yeah, it would be more work -- unexpire is the simplest, both to check for and to change.

**Comment by CarlosNZ** [comment]
> On that note - due dates will be part of the emails and LOQ letter if helpful, which sounds like the easiest way to go for now.

Okay, so process would be as follows:
- reviewer submits review with requests for changes, deadline timer begins.
- applicant receives email with LOQ doc and it tells them their deadline
- once applicant re-submits, timer is cancelled.
- if deadline expires, application is set to outcome: EXPIRED
- at that point, applicant can do nothing until reviewer has changed it
- reviewer has a button on the Review home page to "Give more time", which would extend the deadline (change application back to "CHANGES_REQUIRED"

**Questions:**
- do we send another email to applicant when the deadline has been reached?
- do we need mechanism for applicant to communicate with reviewers once deadline has expired? How would they "request" an extension? Should they be able to, or do they just have to "wait and see"? 
- Should the deadline extension just be extending it by the same length of time as the original timer, or should we have some options available for the reviewer to select?
- Should the "time remaining" show in the app for the applicant, like in the List page, perhaps?

**Comment by jagoje** [comment]
Ok here is my attempt to answer the questions:

1.  Yes - an email should be sent.  I will request this template from ARMED once the contract is signed.
2.  I think the simplest way at this time is for the email include contact details for ARMED to allow for an applicant to reach out and get in contact separately to the system. I am open to alternative suggestions if you think it will be simple to include in the system - but I think 
3. Hmmm I am leaning towards options for reviewer to select to make it more robust. But if this is more complex - same length of time is ok.
4.  I mean that would be great, we actually offered this as a customisation but they did not select it. I think if it takes more than 1 day to have this don't worry about it. 
5. I think this a good idea. They get 10 working days. Maybe 2 days out is appropriate.
6.  I recommend any reviewer who can see the review home page for simplicity.

**Comment by CarlosNZ** [comment]
### Suggested solution:

- Have a pre-defined/agreed "eventCode" that will always be used for "application deadlines" -- e.g. `appDeadline`
- Process of setting/cancelling/expiring deadline can then work with existing event scheduler system in template actions, as normal:
  - ON_APPLICATION_SUBMIT: cancel `appDeadline` event
  - ON_REVIEW_SUBMIT: if status = CHANGES_REQUIRED, set `appDeadline` scheduled event
  - ON_SCHEDULE: set OUTCOME=EXPIRED

- New endpoint `/extend-application`, checks permission in JWT before allowing, but takes parameters:
  - applicationId / serial
  - eventCode (would always be "appDeadline" from front-end in this case, but in theory same endpoint could be used for other scheduled events/expiries)
  - extension time (optional, default just uses the same duration as original deadline)
- this endpoint would work in a similar way to the "preview-action" endpoint, in that it would simulate a trigger event, in this case thew new "ON_EXTEND" trigger.
- We would then have actions defined in template_action for "ON_EXTEND", which, in this case would be: changeOutcome to "PENDING" and changeStatus to "CHANGES_REQUIRED" (i.e reversing the previous expiry). Note that this would run fine even if the application wasn't already past deadline, so can be used to push deadline back before it's actually expired if we need to.
- Access to the "extend" functionality would need to be defined with a permissionName (or array of) per template, or template_stage. Not sure best place to store this, but perhaps an additional column on the "template_stage" table? We'd need to also return this info as part of the "template" structure

- To get the deadline to show up in the application list table, we'd need to add a computed column to the "application_list" function that retrieves the upcoming deadline based on looking up the "trigger_schedule" table for "appDeadline" events that are active (there should only be one at a time).

Then in the front-end:
- new column in Application List to show "Deadline"
- Review Home page -- the top summary area would have an additional field showing "Applicant Deadline". If the reviewer logged in has permission (we check the structure), then we show a button something like this:
![Extend button preview](https://user-images.githubusercontent.com/5456533/177903088-33e66203-ddea-4e27-9a79-1bfa41082aa8.png)
- ... which would load a small modal with some kind of duration selector.
- on submit, call the `/extend-application` endpoint, wait for response, then call application .reload() (There's a method for this on application structure already)

Would also need:
- bit of extra logic in "Timeline" back-end to create "extended deadline" event, and in front-end to parse it.

I think that covers the guts of it. I'm not sure about the permission aspect. I think it definitely needs to be permission-restricted, but I'm not sure how we define it -- should it be per stage, or overall for the whole application? And should we restrict it to the same permission as the current "review" permission needed for this template, or should it be defined separately? (And where?)

**Comment by CarlosNZ** [comment]
> * I think the simplest way at this time is for the email include contact details for ARMED to allow for an applicant to reach out and get in contact separately to the system. I am open to alternative suggestions if you think it will be simple to include in the system

Yeah, that seems the simplest for now. We don't currently have any communication channels open to the applicant other than through the application itself, so for now let's leave that for outside the system. Need to remember to provide some kind of contact info in the correspondence somewhere.

> * Hmmm I am leaning towards options for reviewer to select to make it more robust. But if this is more complex - same length of time is ok.

This part is probably not much harder either way. Maybe just a simple "number of days" selector would do. 

> * I mean that would be great, we actually offered this as a customisation but they did not select it. I think if it takes more than 1 day to have this don't worry about it.

It would be less than a day, I think. But can do it last as it other aspects wouldn't be dependent on it.

> * I recommend any reviewer who can see the review home page for simplicity.

I'm concerned that senior staff wouldn't want low-level screeners just handing out extensions willy-nilly. I'd suggest that, by default, whatever permission is needed for the current review stage is required to add an extension. But I think we should also be able to configure it more specifically (though not 100% where, as per suggestion solution above) to allow senior staff to extend deadlines, say.
