### ISSUE TITLE
Config option to connect to online server

### ISSUE THREAD

**Issue by CarlosNZ** [openmsupply/conforma-web-app#1268]
I think it would be useful in development to be able to use a remote back-end when developing front-end. Some things are just easier to test with a live server, as you can pick up on bugs that might only occur with a realistic network speed as opposed to the almost-instant response we get from local server.

We can either use `.env` or another local (non-committed) file to put the server url in, and the existing "config.ts" should check this for a custom value, or default to its current value.

**Comment by CarlosNZ** [comment]
Maybe something you could do @fergie-nz ?

**Comment by CarlosNZ** [comment]
Sorry, @fergie-nz I just did this quickly. ;)

**Comment by fergie-nz** [comment]
No worries!
