### ISSUE TITLE
Differentiate between "Admin" and "SysAdmin"

### ISSUE THREAD

**Issue by CarlosNZ** [openmsupply/conforma-web-app#1270]
This will be needed for Angola so it needs to be part of Phase 2 work.

The issue is, we need to be able to give senior staff "administrative" rights, which would allow them to access "Admin" category templates such as "Grant permissions", "Manage docs", etc, but NOT have access to our actual "isAdmin" permission stuff such as the template builder.

### Suggested solution (needs further discussion and agreement):

- Terminology: to avoid confusion, "Admin" refers to staff-admin stuff, that a senior staff member would have access to. And what we're currently calling "Admin" (i.e. template builder, etc), will be called "SysAdmin". Senior staff will be "Admin" , but only developers (to start with) will have the actual "isSysAdmin" permissions.
- Therefore first thing will be to go through and change the name of the "isAdmin" permission to "isSysAdmin", otherwise it's going to be really confusing. This will require changing on all templates and the hard-coded "isAdmin" permission in the codebase
- Make the current "Admin" menu just for "staff admin" stuff. Currently is displays system admin stuff and "Admin"-category templates, but it should just be "Admin"-category templates
- The proper "sysAdmin" stuff should be accessed from our special little "Dev" menu in the top-right that currently only shows in development mode. We'll need to do a bit of work making this a bit nicer and useable, and also find a way to still do our "dev" stuff (i.e. quickly change user) when in dev mode.
- Need to update templates that use the "isAdmin" apply permission to use whatever the senior administrator's permission is going to be.

**Comment by CarlosNZ** [comment]
I'm slightly concerned that trying to rename "admin" and "isAdmin" to "sysAdmin" and "isSysAdmin" throughout might be more trouble than it's worth (since it affects quite a few areas).

Wondering if we can just keep the existing "admin" permission, and call the other one something else -- perhaps "systemManager"?

**Comment by nmadruga** [comment]
Yes, it might be better idea to keep things as they are and just move what is required to the new user that we create for System management. I liked this user name also. Let me know if you are already looking on it other wise I will see if I can be any help on that

**Comment by CarlosNZ** [comment]
Okay, going to go with `admin` (leave it as it for proper "dev" tasks), and `systemManager` for permissions for the "admin-ey" templates.

We all happy with that @nmadruga @andreievg ?
