### ISSUE TITLE
Improvement: TB Actions in alphabetical order

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/conforma-web-app#1287]
Not required for Phase2, but added since it was 5 minutes work and improved life of who is doing configuration : P

It's not showing on alphabetical order currently - but it should use the description/title of actions to show in order:

![Image](https://user-images.githubusercontent.com/16461988/184560115-688eb841-28d7-46ae-8af6-66a83814980e.png)

**Comment by CarlosNZ** [comment]
I agree that they should be in a better order, though I'm not sure "alphabetical" is an improvement.

**Comment by nmadruga** [comment]
Oh, it does help my finding of actions haha

I have made a quick PR for that already
