### ISSUE TITLE
Full horizontal list doesn't render upon log in.

### ISSUE THREAD

**Issue by fergie-nz** [openmsupply/conforma-web-app#1291]
List is failing to render fully for Admin - unsure yet if this is affecting other users such as internal or external client users.

Toolbar won't show all options on log in. After refreshing, all options are rendered. It seems that the missing item can vary. Possibly a back-end issue.

On initial log in:

![incompleteAdminList](https://user-images.githubusercontent.com/90807420/185244701-b03b0e86-fea8-4af2-bde3-01aba57201f0.gif)

After refreshing:

![refreshedAdminList](https://user-images.githubusercontent.com/90807420/185244737-feb8b9e6-bbe9-4f94-ada4-a2fc2c557a60.gif)

**Comment by fergie-nz** [comment]
Only affects admin users and not in a major way. Probably not a high priority.

**Comment by CarlosNZ** [comment]
Good catch, should be an easy fix. I'll take care of it.

**Comment by fergie-nz** [comment]
This affects System Manager so is also a UX issue.
