### ISSUE TITLE
Option to auto-assign all sections to reviewer (even when it's not last level)

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/conforma-web-app#1299]
Currently the auto-assignment to all sections only happens (after the reviewer is selected in one of the sections) when the  stage only has one level or when this is the last level review. We would like to add a new option to have the auto-assignment switched on for a specific stage/level.

### Implement in the front-end
Don't have any option for the template. just add helper to assign one reviewer to all the available sections (and if this person doesn't have permissions to one section it will not get assigned to that section...) 
Add a dropdown at the top and list all possible reviewers (from each section's dropdown)

Let's see if this simpler option is valid.

**Comment by CarlosNZ** [comment]
If all the required data is fetched in the parent component and passed to each Assignment row, then should be a fairly simple job. If each Assignment row does it's own query, then it'll be a bit trickier. I'll have a quick look at this this morning and report back.
