### ISSUE TITLE
Remove date and update logic to check due-dates at the end of the day

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/conforma-web-app#1300]

**Comment by CarlosNZ** [comment]
FYI -- the scheduler time is a config setting -- in preferences.json

**Comment by nmadruga** [comment]
> FYI -- the scheduler time is a config setting -- in preferences.json

Cool. Good to know! One other change that would be required is to not show the time (just keep the date) on the UI.

I wonder if this can be set to make the due-date checking run at the end of the day (even thought the server uses a different time as it is in the country). My concern is it shouldn't run in the middle of the day.

**Comment by CarlosNZ** [comment]
> I wonder if this can be set to make the due-date checking run at the end of the day (even thought the server uses a different time as it is in the country). My concern is it shouldn't run in the middle of the day.

Yes, that part is no problem -- the scheduler is based on server's local time.

However, one hurdle I've just realised is that we only have one schedule for all scheduled actions. It's currently set to every half hour. I can make it once a day, but that'll apply to ALL scheduled actions.

I *think* this should be okay (for Angola), but can you think of any potential problems?
