### ISSUE TITLE
Bug: Intermittent ProdRegistration error on submit (GraphQL Payload too large)

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/conforma-web-app#1302]

**Comment by nmadruga** [comment]
@CarlosNZ I have listed this as one of the bugs that is possibly fixed (without exact changes to it) have you had a look on that one already? I think the nature of this being hard to recreate will make it difficult to fix likewise #1312

**Comment by CarlosNZ** [comment]
Right, thanks for the reminder. I'll see if I can replicate it.

**Comment by CarlosNZ** [comment]
Found the problem: it's getting a GraphQL error "Payload too large"

The `variables` object is enormous, as it includes patches for every response, and some of them have very large `value` objects.

Thinking we can probably change the "application submit" mutation to not include the "value" field of the responses, as they should already be saved (updated as they go). The only value the responses really need to change on submission is the "status: SUBMITTED" field.

Does this sounds reasonable?

**Comment by nmadruga** [comment]
> Thinking we can probably change the "application submit" mutation to not include the "value" field of the responses, as they should already be saved (updated as they go). The only value the responses really need to change on submission is the "status: SUBMITTED" field.
> 
> Does this sounds reasonable?

Seems pretty good solution to me. I also would suggest that we use one of those cool triggers to set the status: SUBMITTED in the back-end, so we shouldn't need to send the array of applicationResponses at all

**Comment by CarlosNZ** [comment]
> Seems pretty good solution to me. I also would suggest that we use one of those cool triggers to set the status: SUBMITTED in the back-end, so we shouldn't need to send the array of applicationResponses at all

Yeah, I could incorporate it into the trigger/function we made the other day, as that already detects "submitted" state.

**Comment by CarlosNZ** [comment]
> > Seems pretty good solution to me. I also would suggest that we use one of those cool triggers to set the status: SUBMITTED in the back-end, so we shouldn't need to send the array of applicationResponses at all
> 
> Yeah, I could incorporate it into the trigger/function we made the other day, as that already detects "submitted" state.

Actually, I don't think this would work as well -- I was thinking of review_responses, but this is for application_responses.

I think a back-end trigger will be a bit convoluted in this case, as we'd have to update application_responses ON_UPDATE of application, and we'd need to add some logic to figure out exactly which ones to update. Probably easiest to keep it as it is with the front-end mutating the responses directly (just not the values).
