### ISSUE TITLE
Bug: Problem with review in stage 2 after LOQ done in stage 1 (maybe related to user's permission)

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/conforma-web-app#1304]

**Comment by fergie-nz** [comment]
I believe this is the same issue described by Jess.

External user submits an application
Application is triaged
Application is reviewed as non-conform by both reviewers, and LOQ is given to external user
External user amends form, and resubmits.
Reviewer 1 unassigns themselves from the module which has the amended section
Reviewer 1 submits a conforming review for the remaining modules
Reviewer 2 submits again lists a non-conform and asks for LOQ from the external user.
The external user can no longer make amendments to this form.
Note - If the Reviewer 1 skips step 6, reviewer 2 will be assigned as the first reviewer for the submission, and can't send LOQ without a second opinion.
Snapshot demonstrating this stuck application can be viewed at:
https://drive.google.com/drive/u/0/folders/1XnwGKAq3ZiQJfzl3ZFVlHRozPdakYmNW

reviewer1 / reviewer2 / fergusExt can be accessed with password: pass1234

**Comment by fergie-nz** [comment]
I will test this with new dev merge and see if this is still an issue

**Comment by fergie-nz** [comment]
No longer able to recreate this issue with new dev branch

**Comment by nmadruga** [comment]
Fergus, it will also require the latest snapshot to have the issue resolved
for similar problem
