### ISSUE TITLE
Bug: Same warning is showing regardless of decision (Conform or Non-conform) in the last stage of ProdRegistration

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/conforma-web-app#1305]

**Comment by fergie-nz** [comment]
I'm able to get two different warning messages. 

![A716F353-1887-4B1E-9B0E-A2F88B047EF2](https://user-images.githubusercontent.com/90807420/187301313-ef387173-f01c-4c2c-a575-a63547a48a4d.jpeg)
![9E4F7534-B2A7-4EF6-8707-2D001D42036E](https://user-images.githubusercontent.com/90807420/187301325-c634cb01-7a89-4bd0-91a2-a60a06f4c818.jpeg)
