### ISSUE TITLE
UX issue with dropdown tool to assign reviewer - some options hidden behind banner

### ISSUE THREAD

**Issue by fergie-nz** [openmsupply/conforma-web-app#1313]
Very small thing but causes a lot of UX pain. Can't see all possible reviewers in certain cases when selecting who should review an application.

I propose small change to make the dropdown have a scroll. However I seem to remember discussion on this and we decided against it. I think this particular use case wasn't considered, so worth taking another look.

Alternative option could be force the dropdown list to sit on top of a banner. I think this would be the best solution because then we wouldn't need the scroll which is a bit clunky at times.

![Critical UX! Cannot select all assignments due to dropdown being blocked](https://user-images.githubusercontent.com/90807420/186571995-83d447fb-ad89-498e-b7ef-b2424d32f10f.png)

**Comment by CarlosNZ** [comment]
@fergie-nz Do you have a snapshot I can use with this in order to see the problem?

**Comment by fergie-nz** [comment]
I don't - but you can recreate it using dev tools and have an artificially short screen.

It is a relatively unique case where the number of options is large enough that it displays upwards. It 'fits' on the screen size, but is placed behind the banner.

**Comment by fergie-nz** [comment]
It would only be an issue when the users would create a large number of reviewing users. However when it does occur, it is very annoying and not obvious how to fix it.

**Comment by CarlosNZ** [comment]
> It would only be an issue when the users would create a large number of reviewing users. However when it does occur, it is very annoying and not obvious how to fix it.

I wonder if we can set a max-height for the list and have it scroll within the drop-down. Could make it a search-able dropdown once it gets above a certain number of users too.

I'll have a look.

**Comment by fergie-nz** [comment]
Would it be possible to also have this as a function of screen size? 

I would be worried that it would pop up again if using a small screen.
