### ISSUE TITLE
Improvement for Number plugin

### ISSUE THREAD

**Issue by CarlosNZ** [openmsupply/conforma-web-app#1316]
The "suffix" or "prefix" should be outside the number input box. For two reasons:
- We can have the prefix/suffix appear before anything is entered (which is more informative for user)
- We can keep the input field as a "number" type so it keeps the stepper

**Comment by fergie-nz** [comment]
Increment / decrement buttons still are not showing

**Comment by fergie-nz** [comment]
Stepper buttons not showing was a config issue
