### ISSUE TITLE
Error with assignment for new company registration

### ISSUE THREAD

**Issue by fergie-nz** [openmsupply/conforma-web-app#1329]
No console errors - I am unsure why this is occurring.

![FCC80854-6B2D-4119-9BED-255A430274FC](https://user-images.githubusercontent.com/90807420/187829023-eabb0b9a-39ea-4ad6-b523-535f80ad3af9.jpeg)

**Comment by CarlosNZ** [comment]
Please link to a snapshot and post a URL of which page has this problem. Ta.

**Comment by fergie-nz** [comment]
http://localhost:3000/application/ORG-0050/review?tab=assignment

from this snapshot:
https://drive.google.com/file/d/1d7gdd0vmjgsVCHCmg67eBI-ggkHq01BR/view?usp=sharing

**Comment by CarlosNZ** [comment]
<img width="946" alt="Screen Shot 2022-09-01 at 9 34 48 PM" src="https://user-images.githubusercontent.com/5456533/187882524-2a29a99f-f22c-48a2-92df-889093dadda7.png">

The applicant hasn't even submitted this application yet, hence no review-assignments generated => no valid "assignment" tab yet. 

A staff member would never be looking at a review page for an application that hasn't been submitted yet.

I think we can close this, unless I'm missing something?

**Comment by fergie-nz** [comment]
Sure, sounds good I will close it.
