### ISSUE TITLE
Loading stuck on edit user details submission

### ISSUE THREAD

**Issue by fergie-nz** [openmsupply/conforma-web-app#1334]
After submitting edit user details form, submission fails and form is stuck on loading.

No console logs.

Occurring on the 50008 demo server as well as my local branch.

**Comment by CarlosNZ** [comment]
Hey, thanks for this, good catch. Was a broken REGEX on the email validator -- my bad I think. 🙄

Can you save this repo for things that actually need development work and keep config stuff in the To-Do list (or templates repo if it's for more than just Angola)? Cheers.
