### ISSUE TITLE
Bug: Not changing pages on DataView

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/conforma-web-app#1359]
Go to Database menu and click on one of the lists, for example "External users". You should check one that has more than one page, then click on the next page and see it doesn't change to the next. Even though it shows the page on the URL the data is the same as page 1. Example:

Check that page 1 and 2 are showing the same - I have removed the URL, Logo and organisation name for privacy:
![Screen Shot 2022-09-29 at 3 06 26 PM](https://user-images.githubusercontent.com/16461988/192922542-6b050cbf-24a9-40ce-b6ca-ed05473b148b.png)
![Screen Shot 2022-09-29 at 3 07 10 PM](https://user-images.githubusercontent.com/16461988/192922548-c6fc4118-d923-4880-bd2f-1b7668431518.png)

**Comment by CarlosNZ** [comment]
Fixed in the branch I'm working on right now. ;)
