### ISSUE TITLE
Improvement: There is no feedback on Assignment tab while loading the action for Reviewer

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/conforma-web-app#1378]

**Comment by CarlosNZ** [comment]
What do we think the solution should be here? I'm kind of reluctant to have little spinning "Loading" icons all over the place. Then again, not sure what would be better.

Can we get some suggestions and agree on one before going to far along with this?

It'd be good to have one of those pulsing/strobing ellipsis-type icons ("...") ([like this](https://www.instructionalsolutions.com/hubfs/dot-dot-dot.gif)), but don't want to bloat it with more packages. Can we do something like that with Semantic and some custom CSS?

**Comment by fergie-nz** [comment]
I personally think there is a lot going on in this one ^

But I like progress bars like this:

https://material.io/components/progress-indicators#usage

**Comment by CarlosNZ** [comment]
> I personally think there is a lot going on in this one ^

I just meant the dot-dot-dot, not all the surrounding hoo-ha.

> But I like progress bars like this:

Yeah, that's quite good. If we can get something like that without installing a whole UI library, that'd be good. Also, that one looks good when it fills the width of the container, but in this case it needs to be something that just sits in a small blank space.
