### ISSUE TITLE
Bug: LOQ Send to applicant doesn't display element to be fixed

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/conforma-web-app#1400]
Try to replicate and identify when it happens
Jess tried only adding the element with rejection, not approving others.

**Comment by CarlosNZ** [comment]
If anyone sees this again, please save a snapshot immediately and note the URL.  Thanks :)

**Comment by nmadruga** [comment]
Duplication of https://github.com/openmsupply/conforma-templates/issues/67
