### ISSUE TITLE
Tweak: Name of document showing in documents tab is too long - should use the short version

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/conforma-web-app#1403]
It's in English, and it would be prefered to show the Portuguese name "short version"

**Comment by jagoje** [comment]
![Image](https://user-images.githubusercontent.com/88009219/197893736-1fdae36d-978b-4750-bacc-86713bcc309c.png)

**Comment by CarlosNZ** [comment]
As mentioned in the meeting -- I'm pretty sure this is because files have been re-uploaded with UIDs already in the filenames. Please check this first, I'm fairly sure there's no need for dev work here.

**Comment by CarlosNZ** [comment]
Closing now -- confirmed that this is as I described above. So just be careful when downloading and re-uploading files, please.

![Screenshot 2022-11-07 at 5 12 06 PM](https://user-images.githubusercontent.com/5456533/200224950-15fceb03-f5cb-4be2-8cd3-5b79783c30a1.png)

This  is how it with a normal filename. As you can see, it includes the Carbone template name in the filename, so we'll need to re-name that if want it to be something in particular (or in Portuguese).

**Comment by CarlosNZ** [comment]
If this is a problem still, please open an issue in Templates repo, as there's no dev work required here that I can tell.
