### ISSUE TITLE
Improve assignee selection dropdown

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/conforma-web-app#1408]
As mentioned on the meeting with the client, it would be desirable to have the option to assign yourself at the top of the list. Plus a few other things to improve:
- [x] Allow the dropdown to show scroll for long lists
- [x] Show list in alphabetical order
- [x] Add the option to assign yourself at the top

Note - in order to change to alphabetical order and adding the "Yourself" user to the top proved would be needed to do while improving the complex mechanism in `useGetAssignmentOptions` hook. So that will be pending for when we have more time to do.

**Comment by CarlosNZ** [comment]
> Allow the dropdown to show scroll for long lists

We could use the "DataViewFilterList" component to show a filterable list of names (cos scrolling would still be annoying if there was a long list).
