### ISSUE TITLE
Fiji testing day - Review history still crashing to a blank screen

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/conforma-web-app#1417]

**Comment by CarlosNZ** [comment]
Something to please check:

- Can anyone reproduce this locally? I haven't been able to. If you do see it, can then you then immediately run `yarn migrate` and try again? If the problem persists, then it's something else on top of what I've already fixed. But if it does come right, then there's something not working correctly in the migration code (i.e. it's not running what it's supposed to on the server) so we'll need to fix that.

**Comment by CarlosNZ** [comment]
Should be fixed by https://github.com/openmsupply/conforma-server/pull/952

**Comment by CarlosNZ** [comment]
Closing this now -- pretty sure it's sorted (in v0.4.6-13), please let me know if you see otherwise, @jagoje
