### ISSUE TITLE
Final Decision - Problem to make review

### ISSUE THREAD

**Issue by CarlosNZ** [openmsupply/conforma-web-app#1423]
As pointed out by @fergie-nz on Friday, the Final Decision on 50004 is broken.

When logged in as "basic_reviewer", we get this error in the UI:

![Screenshot 2022-11-06 at 4 22 37 PM](https://user-images.githubusercontent.com/5456533/200152460-145fadf1-45ab-4a03-9ca1-28bf01080b77.png)

When running this locally, the console is reporting an error about calling a hook from somewhere other than the body of a functional component -- and indeed this is the case at line 149 of `ReviewSectionRowAction.tsx`:
```
        const remakeReview = useRemakePreviousReview({
          reviewStructure,
          reviewAssignment,
          previousAssignment,
        })
```

Which would suggest this bit of code has *never* worked, so must not actually be encountered very often. When I change it to circumvent this "if" block and just run `createReview()`, it sometimes works and sometimes complains about row-level permissions -- not sure what's going on there.

Still, it all comes back to the mess that is caused by allowing multiple assignments -- if we get rid of this, then we'll be able to remove a lot of this convoluted logic in the front-end. 

Not sure what the best approach is, we'll need to have a bit of a chat first. I would suggest that we immediately start enforcing proper back-end integrity around review assignments (i.e. not allow multiple assignments) via [this PR](https://github.com/openmsupply/conforma-server/pull/944), then go from there -- fix the problem that then arise whenever something (either an action or the front-end) tries to break this enforcement. This will probably mean a slight regression initially, but IMO will be worth it once we simplify this whole mess. (We'll just have to make sure we don't put any problematic build up online)

Just posting this here now so we have something to start the week with -- but we need to sort this out ASAP or we're going to be plagued by these annoying bugs over and over again.

**Comment by CarlosNZ** [comment]
@nmadruga You can rename this issue once you submit the PR that fixes the hook problem ;)

**Comment by nmadruga** [comment]
> @nmadruga You can rename this issue once you submit the PR that fixes the hook problem ;)

I realised that the PR with this problem is still open. So I'm adding the fix direct to it. I'll tag this issue - and rename now.
