### ISSUE TITLE
Quick fixes in Filter/Sort of Applications list

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/conforma-web-app#1454]
2 bugs noticed in yesterday's UAT Session:

1. When using the link to filter of "Ready to assign"
![Screen Shot 2022-11-25 at 10 30 47 AM](https://user-images.githubusercontent.com/16461988/203865429-b50e9a72-9a61-4867-9904-982bab18b0ec.png)

* no filter is displayed on the Filters at the top
* The problem is that there isn't a way to **Remove** this filter, so users get confused why they can't use other filters and not get proper results...
![Screen Shot 2022-11-25 at 10 19 43 AM](https://user-images.githubusercontent.com/16461988/203865013-2538b8b4-2c29-4ffa-a932-3133b249868a.png)

2. When choose to sort by Stage - the columns swap place (or moved) while the applications were loading
https://user-images.githubusercontent.com/16461988/203865015-2851077c-103d-4066-81ab-bb4ad71fd4e6.mov

**Comment by CarlosNZ** [comment]
> The problem is that there isn't a way to **Remove** this filter, so users get confused why they can't use other filters and not get proper results...

I don't get it -- what's wrong with this?

<img width="748" alt="Screenshot 2022-11-29 at 9 16 37 PM" src="https://user-images.githubusercontent.com/5456533/204475672-a3d938f4-b4e0-4f39-a0af-602e3f41a66d.png">

**Comment by CarlosNZ** [comment]
> 2\. When choose to sort by Stage - the columns swap place (or moved) while the applications were loading
>         https://user-images.githubusercontent.com/16461988/203865015-2851077c-103d-4066-81ab-bb4ad71fd4e6.mov

Assigning myself this one -- should be quite an easy fix I think. I'll need a little more clarification to understand what the first one needs.

**Comment by CarlosNZ** [comment]
> > 2. When choose to sort by Stage - the columns swap place (or moved) while the applications were loading
> > https://user-images.githubusercontent.com/16461988/203865015-2851077c-103d-4066-81ab-bb4ad71fd4e6.mov
> 
> Assigning myself this one -- should be quite an easy fix I think. I'll need a little more clarification to understand what the first one needs.

Hmm, having a closer look at the video here, the columns aren't actually changing. What's happening is that the table sets the column widths automatically. And the widths it generates when there is no content is different to the actual widths once the data loads.

Not sure what to do about this. One option is to have the "Loading" spinner appear over the top of the current list (so we don't clear the data), which will keep the columns as they are. However, this will be a non-trivial amount of work for what is effectively a minor cosmetic improvement, so I'd think that definitely falls outside the scope of what we should be doing at the moment (development-wise). I think we'd need specific approval to spend any time on this, and it's certainly not a "must have".

**Comment by nmadruga** [comment]
> > The problem is that there isn't a way to **Remove** this filter, so users get confused why they can't use other filters and not get proper results...
> 
> I don't get it -- what's wrong with this?
> 
> <img alt="Screenshot 2022-11-29 at 9 16 37 PM" width="748" src="https://user-images.githubusercontent.com/5456533/204475672-a3d938f4-b4e0-4f39-a0af-602e3f41a66d.png">

I think that what happened is that the number wasn't showing on the summary of filters... since the number was not showing on the top it wasn't clear to the user that it has been filtered by "Assigned to you".
I'm unsure why in your attempt this bug didn't happen though. Did you get there from clicking on the filter on the Dashboard?

**Comment by fergie-nz** [comment]
Expanding on this:

Occurs specifically when user selects a filtered link for product registration where the filter is related to assigner actions.

![BA5B23EB-914F-4383-B65F-D0F197437E00](https://user-images.githubusercontent.com/90807420/205522547-484c9e81-d0e8-42f2-9bfe-143dd0bd18ba.jpeg)

This renders a filtered list, however how it is being filtered is not visible in the UI which could be confusing for the user.
Selecting the filterdrop down list shows no filtering is being conducted. Probably because assigner related filters were removed from this list.

![56C4E78A-FACE-4E03-8712-60CD824FB513](https://user-images.githubusercontent.com/90807420/205522567-b11b0526-2ddb-495d-9ccf-3898a5165734.jpeg)

Nicole and I had a brief chat and thought probably not crucial bug fix, but is a low hanging UI improvement.
