### ISSUE TITLE
"Default" values not working properly inside listBuilder

### ISSUE THREAD

**Issue by CarlosNZ** [openmsupply/conforma-web-app#1495]
I don't think we need this right now, but we should fix it sometime soon.

**Comment by jagoje** [comment]
@CarlosNZ - sorry what is this one?

**Comment by CarlosNZ** [comment]
Defaults values for form fields aren't working within listBuilders. If you try and set one, it'll just show up blank.

Would be good to fix, but I'm not sure how complicated it is.
