### ISSUE TITLE
Mobile layout -- smaller tasks

### ISSUE THREAD

**Issue by CarlosNZ** [openmsupply/conforma-web-app#1553]
Part of Epic #1548 

- [x] Login page: reduce padding on outer container so form box fills more of the screen:
![Image](https://github.com/openmsupply/conforma-web-app/assets/5456533/909b5941-6221-4126-a6ac-c082a5a341e7)
- [x] Data View tables -- check filters wrap correctly
- [x] #1581
- [x] ListBuilder modals -- add a close button (for mobile only) 
- [x] Listbuilder "Inline" view (accordion) -- problem with extending out of container (need to be careful with this, as sometimes they contain a table, and we've intentionally let it extend past the container in normal application view, so might need some re-thinking)
- [x] Pagination - check pagination wrap/fit correctly on mobile.

**Comment by guatemartin** [comment]
Added task to check pagination works on mobile.

**Comment by CarlosNZ** [comment]
>  * [x]  Data View tables -- check filters wrap correctly

I checked -- they're all good 👍

>  * [x]  Pagination - check pagination wrap/fit correctly on mobile.

Done in #1577

**Comment by guatemartin** [comment]
Broke out ListBuilder into #1581 as they will need more detailed work.

**Comment by CarlosNZ** [comment]
Closed by #1575
