### ISSUE TITLE
ListBuilders -- check the more complex ones and make sure they look okay

### ISSUE THREAD

**Issue by guatemartin** [openmsupply/conforma-web-app#1581]
ListBuilders have quite a bit going on in them.  None of them scale well into mobile.  Needs more discussion of how mobile layout should look and function.  Should they even be in mobile?
Bringing tasks over from #1553 to complete with the rest of these.

- [x] Check that the list builders scale down for mobile
- [x] ListBuilder modals -- add a close button (for mobile only)
- [x] Listbuilder "Inline" view (accordion) -- problem with extending out of container (need to be careful with this, as sometimes they contain a table, and we've intentionally let it extend past the container in normal application view, so might need some re-thinking)

**Comment by CarlosNZ** [comment]
I've got these looking mostly okay now. It will be hard to test every possible layout and use case though, so we'll probably be trouble-shooting as we go along for a few weeks on these.

**Comment by CarlosNZ** [comment]
Closed by #1589
