### ISSUE TITLE
Review URL structure and routing

### ISSUE THREAD

**Issue by CarlosNZ** [openmsupply/conforma-web-app#200]
Figure out URL strucure that allows specific review/stage details, and handle parameters/query in Routing

**Comment by CarlosNZ** [comment]
Review URLs:

`/review/[appSerial]/[reviewId]`

If we're having a Start (pre-create) page, it would be:

`/review/<applicationSerial>/start` which would have a "Start" button that creates a new review and re-directs to it.

For consolidate it could be:

`/review/[appSerial]/[reviewId]?mode=consolidate`

Or do we want a whole seperate `/consolidate` path?

**Comment by andreievg** [comment]
I feel like we do need a stage parameter somewhere. And if we do have one, do we really need reviewId ?

**Comment by andreievg** [comment]
Just a further refinement to review url logic:

`/review/[appSerial]/[reviewId]`

* if review does not exist 404 it
* if review exists and status = 'submitted', show non editable review
* if review exists and status = 'Draft', show editable review
* if review exists and status = 'Changes Require' or 'Review Pending' go to `/review/[appSerial]`

`/review/[appSerial]`

Based on current application **stage**, and current **user**. (for ALL of the below)

* if review does not exist, check if there are any assignments:
   * if yes, then show _**start review**_
   * if no, then 404
* if review exists and status = 'Changes Require' or 'Review Pending' then show _**continue review**_
* if review exists with other status go to `/review/[appSerial]/[reviewId]`

 _**start review**_ -> create review and all responses
_**continue review**_ -> duplicate responses, change status to 'draft'

On top of all of that, we should include similar logic to review.trigger != null

Consolidation to be refined further in further issues (but I would imagine will be pretty much the same)

**Comment by nmadruga** [comment]
I think we can have a similar Diagram as in #269 done for this one and then we can close this issue? Will target it to be done as part of Sprint 17.

**Comment by CarlosNZ** [comment]
Pretty sure this is all good how it is now.
