### ISSUE TITLE
Deliverables Brainstorm 

### ISSUE THREAD

**Issue by andreievg** [openmsupply/conforma-web-app#22]
### Initial setup
Epics: #74, #75, #76, #77.
* Back End and Front end Repo :heavy_check_mark:
* Intiate schema scripts :heavy_check_mark:
* Postgraphile (connecting to schema) :heavy_check_mark:
* Basic Actions Plugins :heavy_check_mark:
* Routing and Navigation :heavy_check_mark:

### Basic Application Skeleton (Use Registration)
Epics: #70, #73, ...continuing #74, #75.
* End point for user registration :heavy_check_mark:
* Hard coded application template :heavy_check_mark:
* Front end creates application from template :heavy_check_mark:
* Form Element Plugins
    * Core form elements plugins work :heavy_check_mark:
    * Remote form element plugins work (not require for basic application skeleton)
* Display created application
    * Show all form elements in application, handles state change (responses) :heavy_check_mark:
* Submit application
    * Auto approve and Add User Action :heavy_check_mark:
    * Send email confirmation, auto approve and fully add user on confirmation (not require for basic application skeleton)

Using evaluator for:
* Visibility :heavy_check_mark:
* Editability
* Validation :heavy_check_mark:
* Field Selection

### Basic Application Mode (Company Registration & basic Drug registration)
Epics: #78, #94, #96, #97, #98  ...continuing #73.
* Display Available Application Types (by permissions)
* List Applications 
* Create Applications
* Navigate to Applications
* Submit Applications
* View and amend change requests

### Permissions
Epics: #95, #93
* Login endpoint and token (extract from DB)  :heavy_check_mark:
* Front End Knows ?
    * What applications user can create
    * What applications user can review
    * What applications user can assign
* Create permission types
* Assign permissions to templates
* Assign permissions to users
    * Form Element Plugin (i.e when Applying for Company Registration)
    * Action to assign permissions when application is approved
* Extras
    * Master admin permissions

### Basic Assign Skeleton (Company Registration)
Epic: #99
* Hard coded submitted application and users with review permission
* Can assign sections to users with permissions on those sections

### Basic Review Skeleton (Company Registration)
Epic: #100
* Hard coded submitted application, and review assigned to user
* Can start/create review
* Can review each question
* Can submit review

### Basic Consolidation Skeleton (Company Registration) 
* Hard coded submitted application, and submitted review and 
* Can select observations for LOQ
* Can overwrite review
* Submit review/consolidation
* Action: for observations 
* Action: for approval (next stage)

------
## New Epics
- Dashboards
- File upload
- Final approval
- Localisation
- Mobile layout
- Documentation
- Testing
- Hosting
- Admin control - view permissions
- Company control - edit users permissions
- Admin - Template builder
- System settings
- Plugins - UC, mSupply Tender
------

**Comment by andreievg** [comment]
Design Work
  * Make it look like designer
  * Mobile/Desktop

**Comment by CarlosNZ** [comment]
Make production-ready (security, production environment, etc.)

**Comment by andreievg** [comment]
Add estimated times of completion
Add arbitrary effort
Add links/refine epics
