### ISSUE TITLE
Data tables -- filterable, searchable & sortable

### ISSUE THREAD

**Issue by CarlosNZ** [openmsupply/conforma-web-app#977]
First thing to note is that only "simple" fields that return a primitive data type will be search-able/filterable. This means that things like "Formulations", or any of the other fields stored as `JSON` *won't* be search/filterable directly. If we wanted to achieve this, we could add additional columns that just extract the relevant stuff (active ingredients text for example)

The server currently returns a `dataType` field for each (simple) column, and I *think* this should be enough for the front-end to determine what kind of filter to display.

So the work would involve:

### Back-end:
- make sure all filtering/ordering/etc. can be constructed from url query. Most of it is already there, need to check what's missing.
- we might want to add an additional field "isVisible" to column definitions. That's because if we have additional "text" columns for filtering (as mentioned above), we probably don't want to actually display them, as the "fancy" plugin formatted version will still be the primary display column
- might also want to add an "isSearchable" column to specify which fields are searchable by the primary search box.

### Front-end:
- add "sortable" to columns table view, and update (url) query on click
- Use existing filter components (from application list), and map them to filterable columns based on data type
- should re-use as much of the existing filtering functionality from Application List as possible.

**Comment by CarlosNZ** [comment]
Since we want to keep the front-end fairly "dumb", it would normally be preferable to have the filter objects built by the back-end based on the front-end url parameters. However, since we have already made `buildQueryFilters` for the applications list, it makes sense to use this and send a fully-formed filter object from the front end. Otherwise we'd only be duplicating all the logic in `buildQueryFilters.ts` in the back-end.

However, this complicates things a bit as sending a structured object in a [GET request is not recommended](https://stackoverflow.com/questions/978061/http-get-with-request-body), so would have to change this to a POST request, which adds its own complications.

Will need to have a bit more of a think about this.

**Comment by CarlosNZ** [comment]
> Will need to have a bit more of a think about this.

I think the best way might be to use the existing `buildQueryFilters` logic in the front end to construct the filter. But then break it up and send the properties as endpoint url params. The back-end then just needs to reconstruct the filter object (doing some type conversion if necessary, but still a lot less logic than the initial params => filter logic)

**Comment by CarlosNZ** [comment]
> However, this complicates things a bit as sending a structured object in a [GET request is not recommended](https://stackoverflow.com/questions/978061/http-get-with-request-body), so would have to change this to a POST request, which adds its own complications.

This only affects the Table view, so I think just changing that one to a POST request is probably best.

**Comment by jagoje** [comment]
@CarlosNZ is this still open?

**Comment by CarlosNZ** [comment]
Yeah, it's pretty much done. There's just one outstanding PR tidying up a few minor loose ends. I'll close this -- Thanks.
